### ISSUE TITLE
Get Types from Poll

### ISSUE THREAD

**Issue by eschiendorfer** [nataniel/bggxmlapi2#12]
Is it possible to get the types of the polls?

Let's say for example the famous 7 Wonders: https://www.boardgamegeek.com/boardgame/68448/7-wonders

- 62.2% say it's a strategy game
- 33.7% say it's a family game

Can I get this Info somehow by this API?

Thanks a lot for your response and your work in general!

**Comment by nataniel** [comment]
Hello,

The only available polls are "suggested number of players", "language dependence" and "suggested player age":
https://www.boardgamegeek.com/xmlapi2/thing?id=68448&stats=1

"language dependence" poll is used, when calling Thing#getLanguageDependenceLevel(), others are not covered right now.

**Comment by eschiendorfer** [comment]
Thanks for your fast reply! 

Edit: you are right. I messed the info up :( But now I wonder if it's possible to get rank info. Cause this is in xml.
