### ISSUE TITLE
Get only expansions

### ISSUE THREAD

**Issue by jschouwstra** [nataniel/bggxmlapi2#2]
Hi Nataniel,

is there a way to get only "things" that are expansions?

**Comment by nataniel** [comment]
There is no way to get a set / collection of things, currently you can only get one "thing":
`$thing = $client->getThing(39856, true);`

and then you can get its expansions:
```
$expansions = $thing->getBoardgameExpansions();
foreach ($expansions as $expansion) {
  $item = $client->getThing($expansion);
  echo $item->getName();
}
```

**Comment by jschouwstra** [comment]
This is very useful, thanks!
This was basically what I wanted :)
🥇
