### ISSUE TITLE
How do you search for the object's name instead of id with your API?

### ISSUE THREAD

**Issue by jschouwstra** [nataniel/bggxmlapi2#3]
How do you search for the object's name instead of id?
Like this but with similar syntax:

// get results of"Dixit"

https://www.boardgamegeek.com/xmlapi2/search/?query=dix

$results = $client->searchThing('dix', true);
Something like this would be a great feature!

**Comment by nataniel** [comment]
Good idea!
I've just published a 1.1.2 release, with:

```
$results = $client->search('Domek');
echo count($results);

$things = [];
foreach ($result as $item) {
    var_dump($item->getName());
    $things[] = $client->getThing($item->getId());
}
```

Enjoy!
