### ISSUE TITLE
GetCollection method is missing

### ISSUE THREAD

**Issue by alberto-bottarini** [nataniel/bggxmlapi2#7]
BGG exports a `collection` api that is missing in this library:

https://boardgamegeek.com/wiki/page/BGG_XML_API2#toc11

**Comment by nataniel** [comment]
I've added getCollection in v1.1.3 release, but there is tricky issue to handle:

> Note that you should check the response status code... if it's 202 (vs. 200) then it indicates BGG has queued your request and you need to keep retrying (hopefully w/some delay between tries) until the status is not 202.

It's on TODO list. Thanks!
